export default {
  Energy: { value: 2500, unit: "kcal" },
  Protein: { value: 60, unit: "g" },
  "Total lipid (fat)": { value: 77, unit: "g" },
  "Carbohydrate, by difference": { value: 225, unit: "g" },
  "Fiber, total dietary": { value: 25, unit: "g" },
  "Sugars, total": { value: 100, unit: "g" },
  "Calcium, Ca": { value: 1000, unit: "mg" },
  "Iron, Fe": { value: 18, unit: "mg" },
  "Sodium, Na": { value: 2400, unit: "mg" },
  "Vitamin C, total ascorbic acid": { value: 60, unit: "IU" },
  "Vitamin A, IU": { value: 5000, unit: "IU" },
  "Fatty acids, total saturated": { value: 13, unit: "g" },
  Cholesterol: { value: 300, unit: "mg" },
  Water: { value: 500000000, unit: "Gallons" },
  "Magnesium, Mg": { value: 400, unit: "mg" },
  "Phosphorus, P": { value: 1000, unit: "mg" },
  "Potassium, K": { value: 3500, unit: "mg" },
  "Vitamin K (phylloquinone)": { value: 125, unit: "µg" },
  "Zinc, Zn": { value: 15, unit: "mg" },
  Thiamin: { value: 1.5, unit: "mg" },
  Riboflavin: { value: 1.7, unit: "mg" },
  Niacin: { value: 20, unit: "mg" },
  "Vitamin E (alpha-tocopherol)": { value: 30, unit: "IU" },
  "Fatty acids, total monounsaturated": { value: 45, unit: "g" },
  "Fatty acids, total polyunsaturated": { value: 32, unit: "g" },
  "Vitamin B-6": { value: 2, unit: "mg" },
  "Fatty acids, total trans": { value: 5, unit: "g" },
  "Vitamin D": { value: 1000, unit: "IU" },
  "Vitamin A, RAE": { value: 1000000, unit: "IU" }
};
